# fish completion for libex-core, generated from the command definitions, do not edit by hand
complete -c libex-core -f
complete -c libex-core -n __fish_use_subcommand -s h -l help -d 'show this help message and exit'
complete -c libex-core -n __fish_use_subcommand -l version -d 'show the version number and exit'
complete -c libex-core -n __fish_use_subcommand -s q -l quiet -d 'print only the final error line'
complete -c libex-core -n __fish_use_subcommand -s v -l verbose -d 'more detail on standard error, repeat as -vv for debug output with tracebacks'
complete -c libex-core -n __fish_use_subcommand -a book -d 'look up books and chapters'
complete -c libex-core -n __fish_use_subcommand -a series -d 'look up a series'
complete -c libex-core -n __fish_use_subcommand -a search -d 'search the catalog'
complete -c libex-core -n __fish_use_subcommand -a quick-search -d 'search by keywords through suggestions'
complete -c libex-core -n __fish_use_subcommand -a abs -d 'search in the Audiobookshelf provider shape'
complete -c libex-core -n __fish_use_subcommand -a narrator -d 'look up books by narrator'
complete -c libex-core -n __fish_use_subcommand -a completion -d 'print a shell completion script'
complete -c libex-core -n __fish_use_subcommand -a config -d 'show how requests would leave this machine'
complete -c libex-core -n '__fish_seen_subcommand_from book; and not __fish_seen_subcommand_from get bulk chapters' -a 'get bulk chapters'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from get' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from get' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l file -d 'read more ASINs from this file, or from standard input when it is -'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from chapters' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from chapters' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from series; and not __fish_seen_subcommand_from get books' -a 'get books'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from get' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from get' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from search' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from search' -l title -d 'words in the title'
complete -c libex-core -n '__fish_seen_subcommand_from search' -l author -d 'name of the author'
complete -c libex-core -n '__fish_seen_subcommand_from search' -l narrator -d 'name of the narrator'
complete -c libex-core -n '__fish_seen_subcommand_from search' -l publisher -d 'name of the publisher'
complete -c libex-core -n '__fish_seen_subcommand_from search' -l keywords -d 'keywords to match anywhere'
complete -c libex-core -n '__fish_seen_subcommand_from search' -l query -d 'stands in for the title when none is given'
complete -c libex-core -n '__fish_seen_subcommand_from search' -l sort-by -d 'the sort order, using the name Audible gives it'
complete -c libex-core -n '__fish_seen_subcommand_from search' -l limit -d 'results per page, 1 to 50, default 10'
complete -c libex-core -n '__fish_seen_subcommand_from search' -l page -d 'page of results to return, counting from 0 to 9, default 0'
complete -c libex-core -n '__fish_seen_subcommand_from search' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from quick-search' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from quick-search' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and not __fish_seen_subcommand_from search quick-search' -a 'search quick-search'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from search' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from search' -l title -d 'words in the title'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from search' -l query -d 'stands in for the title'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from search' -l author -d 'name of the author'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from search' -l keywords -d 'keywords to match anywhere'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from search' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from quick-search' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from quick-search' -l keywords -d 'the words to search for'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from quick-search' -l query -d 'the words to search for when no keywords are given'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from quick-search' -l title -d 'the words to search for when neither is given'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from quick-search' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from narrator; and not __fish_seen_subcommand_from books' -a 'books'
complete -c libex-core -n '__fish_seen_subcommand_from narrator; and __fish_seen_subcommand_from books' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from narrator; and __fish_seen_subcommand_from books' -l limit -d 'results per page, 1 to 50, default 10'
complete -c libex-core -n '__fish_seen_subcommand_from narrator; and __fish_seen_subcommand_from books' -l page -d 'page of results to return, counting from 0 to 9, default 0'
complete -c libex-core -n '__fish_seen_subcommand_from narrator; and __fish_seen_subcommand_from books' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from completion' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'
complete -c libex-core -n '__fish_seen_subcommand_from config' -s h -l help -d 'show this help message and exit'
