# fish completion for libex-core, generated from the command definitions, do not edit by hand
complete -c libex-core -f
complete -c libex-core -n __fish_use_subcommand -s h -l help -d 'show this help message and exit'
complete -c libex-core -n __fish_use_subcommand -l version -d 'show the version number and exit'
complete -c libex-core -n __fish_use_subcommand -s q -l quiet -d 'print only the final error line'
complete -c libex-core -n __fish_use_subcommand -s v -l verbose -d 'more detail on standard error, repeat as -vv for debug output with tracebacks'
complete -c libex-core -n __fish_use_subcommand -a book -d 'look up books and chapters'
complete -c libex-core -n __fish_use_subcommand -a series -d 'look up a series'
complete -c libex-core -n __fish_use_subcommand -a author -d 'look up an author'
complete -c libex-core -n __fish_use_subcommand -a search -d 'search the catalog'
complete -c libex-core -n __fish_use_subcommand -a quick-search -d 'search by keywords through suggestions'
complete -c libex-core -n __fish_use_subcommand -a abs -d 'search in the Audiobookshelf provider shape'
complete -c libex-core -n __fish_use_subcommand -a narrator -d 'look up books by narrator'
complete -c libex-core -n __fish_use_subcommand -a releases -d 'look up new and upcoming releases'
complete -c libex-core -n __fish_use_subcommand -a completion -d 'print a shell completion script'
complete -c libex-core -n __fish_use_subcommand -a config -d 'show how requests would leave this machine'
complete -c libex-core -n '__fish_seen_subcommand_from book; and not __fish_seen_subcommand_from get bulk chapters' -a 'get bulk chapters'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from get' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from get' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l file -d 'read more ASINs from this file, or from standard input when it is -'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l language -d 'Filter by language (exact match)'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l book-format -d 'Filter by book format (e.g. unabridged)'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l explicit -r -a 'true false' -d 'Filter by explicit'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l whisper-sync -r -a 'true false' -d 'Filter by Whispersync availability'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l has-pdf -r -a 'true false' -d 'Filter by PDF companion availability'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l is-vvab -r -a 'true false' -d 'Filter by VVAB (virtual voice audiobook) status'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l plan-name -d 'Filter by Audible plan name (e.g. US Minerva)'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l rating-better-than -d 'Minimum rating'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l rating-worse-than -d 'Maximum rating'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l longer-than -d 'Minimum length in minutes'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l shorter-than -d 'Maximum length in minutes'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l genre -d 'Filter by genre or tag name (partial match, e.g. fantasy)'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l sort -r -a 'title releaseDate rating lengthMinutes language publisher updatedAt' -d 'sort the books by this field, default is the order they were found in'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from bulk' -l order -r -a 'asc desc' -d 'the direction of --sort, default asc'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from chapters' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from book; and __fish_seen_subcommand_from chapters' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from series; and not __fish_seen_subcommand_from get books search' -a 'get books search'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from get' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from get' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -l language -d 'Filter by language (exact match)'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -l book-format -d 'Filter by book format (e.g. unabridged)'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -l explicit -r -a 'true false' -d 'Filter by explicit'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -l whisper-sync -r -a 'true false' -d 'Filter by Whispersync availability'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -l has-pdf -r -a 'true false' -d 'Filter by PDF companion availability'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -l is-vvab -r -a 'true false' -d 'Filter by VVAB (virtual voice audiobook) status'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -l plan-name -d 'Filter by Audible plan name (e.g. US Minerva)'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -l rating-better-than -d 'Minimum rating'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -l rating-worse-than -d 'Maximum rating'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -l longer-than -d 'Minimum length in minutes'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -l shorter-than -d 'Maximum length in minutes'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -l genre -d 'Filter by genre or tag name (partial match, e.g. fantasy)'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -l sort -r -a 'title releaseDate rating lengthMinutes language publisher updatedAt' -d 'sort the books by this field, default is the order they were found in'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from books' -l order -r -a 'asc desc' -d 'the direction of --sort, default asc'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from search' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from series; and __fish_seen_subcommand_from search' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from author; and not __fish_seen_subcommand_from get search books books-by-name' -a 'get search books books-by-name'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from get' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from get' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from search' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from search' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books' -l language -d 'Filter by language (exact match)'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books' -l book-format -d 'Filter by book format (e.g. unabridged)'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books' -l explicit -r -a 'true false' -d 'Filter by explicit'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books' -l whisper-sync -r -a 'true false' -d 'Filter by Whispersync availability'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books' -l has-pdf -r -a 'true false' -d 'Filter by PDF companion availability'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books' -l is-vvab -r -a 'true false' -d 'Filter by VVAB (virtual voice audiobook) status'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books' -l plan-name -d 'Filter by Audible plan name (e.g. US Minerva)'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books' -l rating-better-than -d 'Minimum rating'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books' -l rating-worse-than -d 'Maximum rating'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books' -l longer-than -d 'Minimum length in minutes'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books' -l shorter-than -d 'Maximum length in minutes'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books' -l genre -d 'Filter by genre or tag name (partial match, e.g. fantasy)'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books' -l sort -r -a 'title releaseDate rating lengthMinutes language publisher updatedAt' -d 'sort the books by this field, default is the order they were found in'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books' -l order -r -a 'asc desc' -d 'the direction of --sort, default asc'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books-by-name' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books-by-name' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books-by-name' -l language -d 'Filter by language (exact match)'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books-by-name' -l book-format -d 'Filter by book format (e.g. unabridged)'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books-by-name' -l explicit -r -a 'true false' -d 'Filter by explicit'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books-by-name' -l whisper-sync -r -a 'true false' -d 'Filter by Whispersync availability'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books-by-name' -l has-pdf -r -a 'true false' -d 'Filter by PDF companion availability'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books-by-name' -l is-vvab -r -a 'true false' -d 'Filter by VVAB (virtual voice audiobook) status'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books-by-name' -l plan-name -d 'Filter by Audible plan name (e.g. US Minerva)'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books-by-name' -l rating-better-than -d 'Minimum rating'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books-by-name' -l rating-worse-than -d 'Maximum rating'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books-by-name' -l longer-than -d 'Minimum length in minutes'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books-by-name' -l shorter-than -d 'Maximum length in minutes'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books-by-name' -l genre -d 'Filter by genre or tag name (partial match, e.g. fantasy)'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books-by-name' -l sort -r -a 'title releaseDate rating lengthMinutes language publisher updatedAt' -d 'sort the books by this field, default is the order they were found in'
complete -c libex-core -n '__fish_seen_subcommand_from author; and __fish_seen_subcommand_from books-by-name' -l order -r -a 'asc desc' -d 'the direction of --sort, default asc'
complete -c libex-core -n '__fish_seen_subcommand_from search; and not __fish_seen_subcommand_from series author abs' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from search; and not __fish_seen_subcommand_from series author abs' -l title -d 'words in the title'
complete -c libex-core -n '__fish_seen_subcommand_from search; and not __fish_seen_subcommand_from series author abs' -l author -d 'name of the author'
complete -c libex-core -n '__fish_seen_subcommand_from search; and not __fish_seen_subcommand_from series author abs' -l narrator -d 'name of the narrator'
complete -c libex-core -n '__fish_seen_subcommand_from search; and not __fish_seen_subcommand_from series author abs' -l publisher -d 'name of the publisher'
complete -c libex-core -n '__fish_seen_subcommand_from search; and not __fish_seen_subcommand_from series author abs' -l keywords -d 'keywords to match anywhere'
complete -c libex-core -n '__fish_seen_subcommand_from search; and not __fish_seen_subcommand_from series author abs' -l query -d 'stands in for the title when none is given'
complete -c libex-core -n '__fish_seen_subcommand_from search; and not __fish_seen_subcommand_from series author abs' -l sort-by -d 'the sort order, using the name Audible gives it'
complete -c libex-core -n '__fish_seen_subcommand_from search; and not __fish_seen_subcommand_from series author abs' -l limit -d 'results per page, 1 to 50, default 10'
complete -c libex-core -n '__fish_seen_subcommand_from search; and not __fish_seen_subcommand_from series author abs' -l page -d 'page of results to return, counting from 0 to 9, default 0'
complete -c libex-core -n '__fish_seen_subcommand_from search; and not __fish_seen_subcommand_from series author abs' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from quick-search; and not __fish_seen_subcommand_from abs' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from quick-search; and not __fish_seen_subcommand_from abs' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and not __fish_seen_subcommand_from search quick-search' -a 'search quick-search'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from search' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from search' -l title -d 'words in the title'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from search' -l query -d 'stands in for the title'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from search' -l author -d 'name of the author'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from search' -l keywords -d 'keywords to match anywhere'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from search' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from quick-search' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from quick-search' -l keywords -d 'the words to search for'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from quick-search' -l query -d 'the words to search for when no keywords are given'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from quick-search' -l title -d 'the words to search for when neither is given'
complete -c libex-core -n '__fish_seen_subcommand_from abs; and __fish_seen_subcommand_from quick-search' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from narrator; and not __fish_seen_subcommand_from books' -a 'books'
complete -c libex-core -n '__fish_seen_subcommand_from narrator; and __fish_seen_subcommand_from books' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from narrator; and __fish_seen_subcommand_from books' -l limit -d 'results per page, 1 to 50, default 10'
complete -c libex-core -n '__fish_seen_subcommand_from narrator; and __fish_seen_subcommand_from books' -l page -d 'page of results to return, counting from 0 to 9, default 0'
complete -c libex-core -n '__fish_seen_subcommand_from narrator; and __fish_seen_subcommand_from books' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and not __fish_seen_subcommand_from new coming-soon categories' -a 'new coming-soon categories'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -l days -r -a '30 60 90 120 240 365' -d 'how many days back to look, default 30'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -l category -d 'only this category, by the id that releases categories prints. Without one the scan is a live sample, not the whole catalog'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -l language -d 'Filter by language (exact match)'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -l book-format -d 'Filter by book format (e.g. unabridged)'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -l explicit -r -a 'true false' -d 'Filter by explicit'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -l whisper-sync -r -a 'true false' -d 'Filter by Whispersync availability'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -l has-pdf -r -a 'true false' -d 'Filter by PDF companion availability'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -l is-vvab -r -a 'true false' -d 'Filter by VVAB (virtual voice audiobook) status'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -l plan-name -d 'Filter by Audible plan name (e.g. US Minerva)'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -l rating-better-than -d 'Minimum rating'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -l rating-worse-than -d 'Maximum rating'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -l longer-than -d 'Minimum length in minutes'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -l shorter-than -d 'Maximum length in minutes'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -l genre -d 'Filter by genre or tag name (partial match, e.g. fantasy)'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -l sort -r -a 'title releaseDate rating lengthMinutes language publisher updatedAt' -d 'sort the books by this field, default is the order they were found in'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from new' -l order -r -a 'asc desc' -d 'the direction of --sort, default desc'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -l days -r -a '30 60 90 120 240 365' -d 'how many days ahead to look, default 30'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -l category -d 'only this category, by the id that releases categories prints. Without one the scan is a live sample, not the whole catalog'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -l language -d 'Filter by language (exact match)'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -l book-format -d 'Filter by book format (e.g. unabridged)'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -l explicit -r -a 'true false' -d 'Filter by explicit'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -l whisper-sync -r -a 'true false' -d 'Filter by Whispersync availability'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -l has-pdf -r -a 'true false' -d 'Filter by PDF companion availability'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -l is-vvab -r -a 'true false' -d 'Filter by VVAB (virtual voice audiobook) status'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -l plan-name -d 'Filter by Audible plan name (e.g. US Minerva)'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -l rating-better-than -d 'Minimum rating'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -l rating-worse-than -d 'Maximum rating'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -l longer-than -d 'Minimum length in minutes'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -l shorter-than -d 'Maximum length in minutes'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -l genre -d 'Filter by genre or tag name (partial match, e.g. fantasy)'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -l sort -r -a 'title releaseDate rating lengthMinutes language publisher updatedAt' -d 'sort the books by this field, default is the order they were found in'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from coming-soon' -l order -r -a 'asc desc' -d 'the direction of --sort, default asc'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from categories' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from categories' -l flat -d 'a flat list, each node carrying its ancestors, instead of a tree'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from categories' -l depth -d 'how many levels to return, 1 is the top level only, default all'
complete -c libex-core -n '__fish_seen_subcommand_from releases; and __fish_seen_subcommand_from categories' -l region -r -a 'us uk ca au de fr it es jp in br' -d 'the Audible marketplace to ask, default us'
complete -c libex-core -n '__fish_seen_subcommand_from completion' -s h -l help -d 'show this help message and exit'
complete -c libex-core -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'
complete -c libex-core -n '__fish_seen_subcommand_from config' -s h -l help -d 'show this help message and exit'
